

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
     name: {{ .Values.appName }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Values.appName }}
